apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: mab3825/final:client
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          # Since we dont have any routes for health and readiness probes, we will comment them out
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 4000
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 4000
          #   initialDelaySeconds: 30
          #   periodSeconds: 10