apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: mab3825/final:client
          ports:
            - containerPort: 1215