# For deploying application purely on docker containers
version: '3'
services:
  client:
    container_name: client
    build: ./client
    ports:
      - '1215:1215'
  auth:
    container_name: auth
    build: ./Auth
    ports:
      - '4000:4000'
  classrooms:
    container_name: classrooms
    build: ./Classrooms
    ports:
      - '4001:4001'
  post:
    container_name: post
    build: ./Post
    ports:
      - '4002:4002'
  event-bus:
    container_name: event-bus
    build: ./event-bus
    ports:
      - '4009:4009'
  db:
    container_name: mongo
    image: mongo
    volumes:
      - dbdata:/data/db
    ports:
      - '27017:27017'
volumes:
  dbdata: