#For pushing to docker hub
version: '3'
services:
  client:
    container_name: client
    build: ./client
    image: mab3825/final:client
  auth:
    container_name: auth
    build: ./Auth
    image: mab3825/final:auth
  classrooms:
    container_name: classrooms
    build: ./Classrooms
    image: mab3825/final:class
  post:
    container_name: post
    build: ./Post
    image: mab3825/final:post
  event-bus:
    container_name: event-bus
    build: ./event-bus
    image: mab3825/final:event-bus