apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-deployment
  namespace: prod
  annotations:
    example.com/annotation-2: "value-2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: class
  template:
    metadata:
      labels:
        app: class
    spec:
      containers:
        - name: class
          image: mab3825/final:class
          ports:
            - containerPort: 4001
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          # Since we dont have any routes for health and readiness probes, we will comment them out
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 4000
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 4000
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          env:
            - name: MONGO_URL
              value: mongodb://mongodatabase:27017/
            - name: EVENT_URL
              value: http://event-bus:4009