apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: mab3825/final:event-bus
          ports:
            - containerPort: 4009
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          # Since we dont have any routes for health and readiness probes, we will comment them out
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 4000
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 4000
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          env:
            - name: MONGO_URL
              value: mongodb://mongodatabase:27017/
            - name: AUTH_URL
              value: http://auth:4000
            - name: CLASS_URL
              value: http://class:4001
            - name: POST_URL
              value: http://post:4000