apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: mab3825/final:post
          ports:
            - containerPort: 4002
          env:
            - name: MONGO_URL
              value: mongodb://mongodatabase:27017/
            - name: EVENT_URL
              value: http://event-bus:4009